import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { ThemeProvider } from "next-themes";
import ThemeToggle from "@/components/ThemeToggle";
import Image from "next/image";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tyreplex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white dark:bg-gray-900 text-black dark:text-white`}>
        <ThemeProvider attribute="class">
        <Header/>
        <div className="text-2xl font-bold">
              <Image src={"/TP-logo-mbl.png"} alt="logo" width={150} height={50}/>
            </div>
            <ThemeToggle />
      <main className="container mx-auto px-4 py-8 dark:bg-gray-800">
        {children}
      </main>
      <Footer/>
      </ThemeProvider>
      </body>
    </html>
  );
}
